-- DishBoard feature platform migration (AI limits + remote feature flags)

create table if not exists public.ai_usage_daily (
    user_id       uuid        not null references auth.users(id) on delete cascade,
    usage_date    date        not null,
    request_count integer     not null default 0 check (request_count >= 0),
    blocked_count integer     not null default 0 check (blocked_count >= 0),
    created_at    timestamptz not null default now(),
    updated_at    timestamptz not null default now(),
    primary key (user_id, usage_date)
);

alter table public.ai_usage_daily enable row level security;

drop policy if exists "ai_usage_select_own" on public.ai_usage_daily;
create policy "ai_usage_select_own"
on public.ai_usage_daily
for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "ai_usage_insert_own" on public.ai_usage_daily;
create policy "ai_usage_insert_own"
on public.ai_usage_daily
for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "ai_usage_update_own" on public.ai_usage_daily;
create policy "ai_usage_update_own"
on public.ai_usage_daily
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create table if not exists public.feature_flags (
    id          bigint generated by default as identity primary key,
    key         text        not null,
    enabled     boolean     not null default false,
    scope       text        not null default 'global' check (scope in ('global', 'user')),
    user_id     uuid        null references auth.users(id) on delete cascade,
    rollout_pct integer     not null default 100 check (rollout_pct >= 0 and rollout_pct <= 100),
    config_json jsonb       not null default '{}'::jsonb,
    updated_at  timestamptz not null default now(),
    unique (key, scope, user_id)
);

alter table public.feature_flags enable row level security;

drop policy if exists "feature_flags_select" on public.feature_flags;
create policy "feature_flags_select"
on public.feature_flags
for select
to authenticated
using (
    scope = 'global'
    or (scope = 'user' and auth.uid() = user_id)
);
